/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package islandfurniturepos;

import javax.swing.JFrame;

/**
 *
 * @author hangsun
 */
public class MainMenu extends javax.swing.JFrame {
    
    private String storeStaffId = null;
    private int location;
    private Long memberId = null;
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    
    public MainMenu(String storeStaffId){
        this();
        
        this.storeStaffId = storeStaffId;
    }
    
     public MainMenu(String storeStaffId,Long memberId){
        this();
        
        this.storeStaffId = storeStaffId;
        this.memberId = memberId;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButtonNewTransactionFurniture = new javax.swing.JButton();
        javax.swing.JButton jButtonLogout = new javax.swing.JButton();
        javax.swing.JButton jButtonNewTransactionRetailProduct = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        javax.swing.JButton jButtonMember = new javax.swing.JButton();
        jLabelMemberId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Island Furniture Point of Sales System");
        jLabel3.setToolTipText("");

        jButtonNewTransactionFurniture.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonNewTransactionFurniture.setText("Create New Transaction for Furniture");
        jButtonNewTransactionFurniture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTransactionFurnitureActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonNewTransactionRetailProduct.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonNewTransactionRetailProduct.setText("Create New Transaction for Retail Product");
        jButtonNewTransactionRetailProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTransactionRetailProductActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        jLabelName.setText("jLabelStaffName");
        jLabelName.setToolTipText("");

        jButtonMember.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonMember.setText("Member Check");
        jButtonMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemberActionPerformed(evt);
            }
        });

        jLabelMemberId.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        jLabelMemberId.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonMember, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonLogout))
                            .addComponent(jButtonNewTransactionRetailProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNewTransactionFurniture, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMemberId)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jLabelMemberId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonNewTransactionFurniture)
                .addGap(18, 18, 18)
                .addComponent(jButtonNewTransactionRetailProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMember)
                    .addComponent(jButtonLogout))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewTransactionFurnitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewTransactionFurnitureActionPerformed
        // TODO add your handling code here:
        location = 1;
        NewTransaction transaction = new NewTransaction(storeStaffId,location,memberId);
        transaction.setVisible(true);
        transaction.setExtendedState(JFrame.NORMAL);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jButtonNewTransactionFurnitureActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        login.setExtendedState(JFrame.NORMAL);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonNewTransactionRetailProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewTransactionRetailProductActionPerformed
        // TODO add your handling code here:
        location = 2;
        NewTransaction transaction = new NewTransaction(storeStaffId,location,memberId);
        transaction.setVisible(true);
        transaction.setExtendedState(JFrame.NORMAL);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonNewTransactionRetailProductActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        if(storeStaffId != null)
        {
            String name = getFullNameById(storeStaffId);
            jLabelName.setText("Login as " + name);
        }
        else
        {
            jLabelName.setText("Please Login");
        }
        
        if(memberId != null){
            jLabelMemberId.setText("Member ID:" + memberId);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButtonMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemberActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        Member member = new Member(storeStaffId);
        member.setVisible(true);
        member.setExtendedState(JFrame.NORMAL); 
        
    }//GEN-LAST:event_jButtonMemberActionPerformed
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewTransactionFurniture;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMemberId;
    private javax.swing.JLabel jLabelName;
    // End of variables declaration//GEN-END:variables

    private static String getFullNameById(java.lang.String arg0) {
        util.login.IFManagerBeanService service = new util.login.IFManagerBeanService();
        util.login.IFManagerBean port = service.getIFManagerBeanPort();
        return port.getFullNameById(arg0);
    }


}
